apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-example
spec:
  selector:
    matchLabels:
      app: jaeger-example
  template:
    metadata:
      labels:
        app: jaeger-example
    spec:
      containers:
      - image: jaeger-example
        imagePullPolicy: Never
        name: jaeger-example
        ports:
        - containerPort: 8080
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector:14267"
